version: '3.8'
services:
  reminders:
    build:
      context: ./backend/reminders
      target: production
    ports:
      - "8080:8080"
    depends_on:
      - postgres

#  reminders-app:
#    build:
#      context: ./frontend/reminders-client
#    ports:
#      - 3000:3000

  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=reminders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data: